/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Movfr                                  */
/*      FILE         :  Movfr.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX62T                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                              


                                                                           
                                                                           
                                                                          
/***********************************************************************/
/*                                                                     */
/*  FILE        :Main.c or Main.cpp                                    */
/*  DATE        :Tue, Oct 31, 2006                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :                                                      */
/*                                                                     */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

#include "Macro.h"
#include "./Timer/Timer.h"
#include "./CAN/CAN.h"
#include "./Flash/Flash.h"
#include "./WatchDog/WatchDog.h"



//version
unsigned char  Version = 2;
unsigned char  Revision = 25;
int MainCLock = 9216000; // Clock input is 9.216MHz




void main(void);
void InitHW(void);
void HeartBeat(void);
void MovfrControl(void);
void InputDebounce(void);



char RUN_PB = 0;
char CAM_SETUP_PB = 0;
char AUTO_PB = 0;
char MANUAL_PB = 0;
char CLOSE_PB = 0;
char OPEN_PB = 0;
char NUDGE_PB = 0;
char HEAVY_PB = 0;
char CLOSE = 0;
char OPEN = 0;
char NUDGE = 0;
char HEAVY = 0;
char GSM = 0;
char AUX = 0;
char SSFO_IN = 0;
char SDO_IN= 0;
char SDC_IN = 0;
char DOL = 0;
char DCL = 0;
char REOPEN = 0;
char REOPEN_LCSE=0;
char FR_Jumper = 0;
char CAN_BaudRate_flag=0;

static unsigned char InputDebounceEna = 0;


//Modify
extern char can_delay_flag;







//-------------------------------------------------------------
//main loop
void main(void)
{

	//set up the MCU I/O Direction
	InitHW();// config  GPIO

	//Init Timer
	InitTimer();

	//Init WatchDog
	InitWatchDog();


	// Check if  Jumper JP2  is  off     FR_Signal-->1  means  JP2 is off
	//check CAN Address
	if(FR_Signal)
		SetCAN_ADDR(RearDoorAddr);


//ZYM 3-1-2018
	//Init CAN
//-	Init_CAN();



	while(1)
	{
		PetDog();
		IncTimer();
		HeartBeat();
		InputDebounce();
//Modify
//-		CanControl();
//-		MovfrControl();

//Modify
		if(can_delay_flag==1)
		{
			CanControl();
			MovfrControl();
		}
	}
}


//-------------------------------------------------------------
/**********************************************/
/**              Init Hardware               **/
/**********************************************/
void InitHW(void)
{
	/* ICLK = EXTAL*8 = 9.216*8 = 73.728 MHz. */
	SYSTEM.SCKCR.BIT.ICK  =  0;
	/* PCLK = EXTAL*1 = 9.216*1 = 9.216 MHz. */
	SYSTEM.SCKCR.BIT.PCK  =  3;


//ZYM 2-20-2018
	//Init ALL Pins as Inputs FIRST
	PORT1.DDR.BYTE=0;
	PORT2.DDR.BYTE=0;
	PORT3.DDR.BYTE=0;
	PORT7.DDR.BYTE=0;
	PORT8.DDR.BYTE=0;
	PORT9.DDR.BYTE=0;
	PORTA.DDR.BYTE=0;
	PORTB.DDR.BYTE=0;
	PORTD.DDR.BYTE=0;
	PORTE.DDR.BYTE=0;
	PORTG.DDR.BYTE=0;



	//--------------------------------
	//Front Rear Door I/O Direction
	FR_Signal_DIR = IO_INPUT;


	//--------------------------------
	//Input Card I/O Direction
	CLOSE_DIR = IO_INPUT;
	OPEN_DIR	= IO_INPUT;
	NUDGE_DIR	= IO_INPUT;
	HEAVY_DIR	= IO_INPUT;


	//--------------------------------
	//CAM I/O Direction
//-	GSM_DIR= IO_INPUT;
//-	AUX_DIR = IO_INPUT;
//-	SSFO_IN_DIR	= IO_INPUT;

	//MSO CAM I/O Direction
//-	SDO_IN_DIR = IO_INPUT;

	//FSC CAM I/O Direction
//-	SDC_IN_DIR	= IO_INPUT;
	DOL_DIR = IO_INPUT;
	DCL_DIR	= IO_INPUT;


	//--------------------------------
	//Reopen I/O Direction
	REOPEN_DIR = IO_INPUT;
	REOPEN_LCSE_DIR=IO_INPUT;


	//--------------------------------
	//LED I/O Direction
//-	HOLD_LED_DIR = IO_OUTPUT;
	DIA_LED_DIR	 = IO_OUTPUT;
	COMM_LED_DIR = IO_OUTPUT;

	//Output Data
//-	HOLD_LED = 0;
	DIA_LED	 = 0;
	COMM_LED = 0;



	//Speed LED I/O Direction
/*//-
	FSO_DIR	= IO_OUTPUT;
	MSO_DIR	= IO_OUTPUT;
	HSO_DIR	= IO_OUTPUT;
	SSO_DIR	= IO_OUTPUT;
	SDC_DIR	= IO_OUTPUT;
	HSC_DIR	= IO_OUTPUT;
*/
	NSC_DIR	= IO_OUTPUT;
//-	NUD_BP_DIR = IO_OUTPUT;

/*//-
	//Output Data
	FSO	= 0;
	MSO	= 0;
	HSO	= 0;
	SSO	= 0;
	SDC	= 0;
	HSC	= 0;
*/
	NSC	= 0;
//-	NUD_BP = 0;



	//--------------------------------
	//Speed Profile to Drive I/O Direction
/*//-
	H_DIR  = IO_OUTPUT;
	M_DIR  = IO_OUTPUT;
	L_DIR  = IO_OUTPUT;
*/

	//Close Direction
	STF_DIR	= IO_OUTPUT;

	//Open Direction
	STR_DIR	= IO_OUTPUT;

	//Heavy Door Direction
	AUX_DRIVE_DIR = IO_OUTPUT;

	//Output Data
/*//-
	H  = 0;
	M = 0;
	L  = 0;
*/
	STF = 0;
	STR	= 0;
	AUX_DRIVE = 0;



	//REOPEN RELAY DIR
	RLY_REOPEN_DIR=IO_OUTPUT;

	//DCL RELAY DIR
	RLY_DCL_DIR=IO_OUTPUT;

	//DOL RELAY DIR
	RLY_DOL_DIR=IO_OUTPUT;

	RLY_REOPEN=0;
	RLY_DCL=0;
	RLY_DOL=0;


	//--------------------------------
	//GAL CAN Baud Rate flag 1 -->  57.6k    0 --> 115.2k
	CAN_BaudRate_HOLD_DIR=IO_INPUT;

	CAN_BaudRate_HOLD=0;
}



//-------------------------------------------------------------
/**********************************************/
/**              Heart Beat                  **/
/**********************************************/
void HeartBeat(void)
{
	static int HeartBeatCase = 0;
	static int BeatCnt = 0;

	//Manual Switch and Setup Switch
	if((MANUAL_PB == 0) && (CAM_SETUP_PB == 0))
	{
//modify
		//"500ms" Cycle
//-		if(LedTimer >= 5) // Toggle LED every 0.5second
		//"1000ms" Cycle
		if(LedTimer>=10) // Toggle LED every second
		{
			LedTimer = 0;

 			DIA_LED ^=1;

			//CAN Communication Indicator
			if(MovfrOnline==1)
			{
//Modify
//-				COMM_LED^=1;
				COMM_LED=DIA_LED;
			}
			else
			{
//Modify
				COMM_LED=1;
//-				COMM_LED=0;
			}
		}
	}
	else
	{
		switch(HeartBeatCase)
		{
//Modify
			case 0:
				LedTimer=0;
				COMM_LED=1;
				DIA_LED=1;
				HeartBeatCase=1;
				break;

			case 1:
//-				if(LedTimer <1)
				if(LedTimer<2)
					break;
				LedTimer = 0;
				DIA_LED ^=1;

//-Willie		COMM_LED^=1;
//-				COMM_LED=DIA_LED;

				BeatCnt++;
//-				if(BeatCnt >=8)
				if(BeatCnt>=6)
				{
					BeatCnt = 0;
					DIA_LED =0;
//-					COMM_LED=0;
					HeartBeatCase = 2;

//Modify
					//CAN Communication Indicator
					if(MovfrOnline==1)
					{
						COMM_LED^=1;
					}
					else
					{
						COMM_LED=1;
					}
				}
				break;
			case 2:
//-				if(LedTimer <5)
				if(LedTimer<10)
					break;
				LedTimer = 0;
				HeartBeatCase = 0;
				break;
		}
	}
}



//-------------------------------------------------------------
/**********************************************/
/**              Movfr Control               **/
/**********************************************/
void MovfrControl(void)
{
	static char OPEN_GLOBAL = 0;
	static char CLOSE_GLOBAL = 0;
 	static char NUDGE_GLOBAL = 0;
	static char HEAVY_GLOBAL = 0;

//-	static char FSO_SIGNAL = 0;
//-	static char MSO_SIGNAL = 0;
//-	static char HSO_SIGNAL = 0;
//-	static char SSO_SIGNAL = 0;
//-	static char SDC_SIGNAL = 0;
//-	static char HSC_SIGNAL = 0;
//-	static char NSC_SIGNAL = 0;
	static char STR_SIGNAL = 0;
	static char STF_SIGNAL = 0;
//-	static char H_SIGNAL = 0;
//-	static char M_SIGNAL = 0;
//-	static char L_SIGNAL = 0;




	//-------------------------------------------------------------
	//Taking "Close, Open, Nudging, and Heavy" Signal Input
    //Auto Switch
	if(AUTO_PB == 1 )
	{
	    //CAN Signal Control
	    if(MovfrOnline == 1)
	    {
	        if(CAN_DOOR_OPEN == 1)
	            OPEN_GLOBAL = 1;
	        else
	            OPEN_GLOBAL = 0;

	        if(CAN_DOOR_CLOSE == 1)
	            CLOSE_GLOBAL = 1;
	        else
	            CLOSE_GLOBAL = 0;

	        if(CAN_DOOR_NUDGE == 1)
	            NUDGE_GLOBAL = 1;
	        else
	            NUDGE_GLOBAL = 0;

	        if(CAN_DOOR_HEAVY == 1)
	            HEAVY_GLOBAL = 1;
	        else
	            HEAVY_GLOBAL = 0;
	    }
	    //Input Card Signal
	    else
	    {
	        if(OPEN == 1)
	            OPEN_GLOBAL = 1;
	        else
	            OPEN_GLOBAL = 0;

	        if(CLOSE == 1)
	            CLOSE_GLOBAL = 1;
	        else
	            CLOSE_GLOBAL = 0;

	        if(NUDGE == 1)
	            NUDGE_GLOBAL = 1;
	        else
	            NUDGE_GLOBAL = 0;

	        if(HEAVY == 1)
	            HEAVY_GLOBAL = 1;
	        else
	            HEAVY_GLOBAL = 0;
	    }
	}
	//Push Button ONLY working in Manual Mode
	else
	{
	    if(OPEN_PB == 1)
	        OPEN_GLOBAL = 1;
	    else
	        OPEN_GLOBAL = 0;

	    if(CLOSE_PB == 1)
	        CLOSE_GLOBAL = 1;
	    else
	        CLOSE_GLOBAL = 0;

	    if(NUDGE_PB == 1)
	        NUDGE_GLOBAL = 1;
	    else
	        NUDGE_GLOBAL = 0;

	    if(HEAVY_PB == 1)
	        HEAVY_GLOBAL = 1;
	    else
	        HEAVY_GLOBAL = 0;
	}

	//Heavy Door to Drive
	if(HEAVY_GLOBAL == 1)
	    AUX_DRIVE = 1;
	else
	    AUX_DRIVE = 0;



/*//-
	//-------------------------------------------------------------
	//Close Direction Speed Profile
	//HSC Speed
	//DCL CAM                                            //Setup Switch
	if((DCL == 0)
		&&(((OPEN_GLOBAL == 0) && (CLOSE_GLOBAL == 1)) || (CAM_SETUP_PB == 1))
 		&&((SDC_IN == 0) && ((NUDGE_GLOBAL == 0) || (CAM_SETUP_PB == 1)))
		//FSC CAM
		)
	{
		HSC = 1;
		HSC_SIGNAL = 1;
	}
	else
	{
		HSC = 0;
		HSC_SIGNAL = 0;
	}



	//FSC(SDC) Speed
	if((DCL == 0) &&
			(((OPEN_GLOBAL == 0) && (CLOSE_GLOBAL == 1)) || (CAM_SETUP_PB == 1))
 			&&(SDC_IN == 1)
			)
	{
		SDC = 1;
		SDC_SIGNAL = 1;
	}
	else
	{
		SDC = 0;
		SDC_SIGNAL = 0;
	}
*/


	//NSC Speed
	if((DCL == 0) &&
			(((OPEN_GLOBAL == 0) && (CLOSE_GLOBAL == 1)) || (CAM_SETUP_PB == 1))
 //-		&&((SDC_IN == 0) && ((NUDGE_GLOBAL == 1) && (CAM_SETUP_PB == 0)))
			&&((NUDGE_GLOBAL == 1) && (CAM_SETUP_PB == 0))
			)
	{
		NSC = 1;
//-		NUD_BP = 1;
//-		NSC_SIGNAL = 1;
	}
	else
	{
		NSC = 0;
//-		NUD_BP = 0;
//-		NSC_SIGNAL = 0;
	}



/*//-
	//-------------------------------------------------------------
	//Open Direction Speed Profile
	//SSO Speed
	if((DOL == 0) &&
			(((OPEN_GLOBAL == 1) && (CLOSE_GLOBAL == 0)) || (CAM_SETUP_PB == 1))
 			&&(SSFO_IN == 1)
			//SSO/FSO CAM

 			&&(SDO_IN == 0)
			//MSO CAM
			)
	{
		SSO = 1;
		SSO_SIGNAL = 1;

	}
	else
	{
		SSO = 0;
		SSO_SIGNAL = 0;
	}

	//HSO Speed
	if((DOL == 0) &&
			(((OPEN_GLOBAL == 1) && (CLOSE_GLOBAL == 0)) || (CAM_SETUP_PB == 1))
 			&&(SSFO_IN == 0)
 			&&(SDO_IN == 0)
			)
	{
		HSO = 1;
		HSO_SIGNAL = 1;

	}
	else
	{
		HSO = 0;
		HSO_SIGNAL = 0;
	}


	//MSO Speed
	if((DOL == 0) &&
		(((OPEN_GLOBAL == 1) && (CLOSE_GLOBAL == 0)) || (CAM_SETUP_PB == 1))
 		&&(SSFO_IN == 0)
		//SSO/FSO CAM
 		&&(SDO_IN == 1)
		)
	{
		MSO = 1;
		MSO_SIGNAL = 1;

	}
	else
	{
		MSO = 0;
		MSO_SIGNAL = 0;
	}

	//FSO Speed
	if((DOL == 0) &&
		(((OPEN_GLOBAL == 1) && (CLOSE_GLOBAL == 0)) || (CAM_SETUP_PB == 1))
 		&&(SSFO_IN == 1)
 		&&(SDO_IN == 1)
		)
	{
		FSO = 1;
		FSO_SIGNAL = 1;
	}
	else
	{
		FSO = 0;
		FSO_SIGNAL = 0;
	}
*/


	//-------------------------------------------------------------
	//Holding
	//STR(Open Direction MUST require "STR" Signal for Holding and Running)
	if((CAM_SETUP_PB == 0)
		&&((DOL == 1) || (OPEN_GLOBAL == 1))
		&&(CLOSE_GLOBAL == 0)
			)
	{
		 STR_SIGNAL = 1;
	}
	else
	{
		 STR_SIGNAL = 0;
	}


	//STF(Close Direction MUST require "STR" Signal for Holding and Running)
	if((CAM_SETUP_PB == 0)
		&&((DCL == 1) || (CLOSE_GLOBAL == 1))
		&&(OPEN_GLOBAL == 0)
		)
	{
		 STF_SIGNAL = 1;
	}
	else
	{
		 STF_SIGNAL = 0;
	}


/*//-
	//-------------------------------------------------------------
	//Speed Profile Output To Drive
	//H
	//HSC Speed             HSO Speed            MSO Speed           FSO Speed
	if((HSC_SIGNAL == 1)|| (HSO_SIGNAL == 1) || (MSO_SIGNAL == 1)|| (FSO_SIGNAL == 1))
	{
		H_SIGNAL = 1;
	}
	else
		H_SIGNAL = 0;


	//M
	//MSO Speed             FSO Speed           FSC Speed            SSO Speed
	if((MSO_SIGNAL == 1)|| (FSO_SIGNAL == 1)|| (SDC_SIGNAL == 1) || (SSO_SIGNAL == 1))
	{
		M_SIGNAL = 1;
	}
	else
		M_SIGNAL = 0;

	//L
	//HSO Speed             FSO Speed           Nudging Speed        SSO Speed
	if((HSO_SIGNAL == 1)|| (FSO_SIGNAL == 1)|| (NSC_SIGNAL == 1) || (SSO_SIGNAL == 1))
	{
		L_SIGNAL = 1;
	}
	else
		L_SIGNAL = 0;



	//HOLDING
	if(((H_SIGNAL == 0) && (M_SIGNAL == 0) && (L_SIGNAL == 0)) &&
		((STF_SIGNAL == 1) || (STR_SIGNAL == 1))
		//Close Direction      Open Direction
		)
	{
		HOLD_LED = 1;
	}
	else
	{
		HOLD_LED = 0;
	}



	H = H_SIGNAL;
	M = M_SIGNAL;
	L = L_SIGNAL;
*/
	STR = STR_SIGNAL;
	STF = STF_SIGNAL;


	//Reopen Relay
	if((REOPEN)||(REOPEN_LCSE))
	{
		RLY_REOPEN=1;
	}
	else
	{
		RLY_REOPEN=0;
	}


	//DOL Relay
	if(DOL)
	{
		RLY_DOL=1;
	}
	else
	{
		RLY_DOL=0;
	}


	//DCL Relay
	if(DCL)
	{
		RLY_DCL=1;
	}
	else
	{
		RLY_DCL=0;
	}
}





/**********************************************/
/**             CheckInput                **/
/**********************************************/
void CheckInput(void)
{
	InputDebounceEna = 1;
}

/**********************************************/
/**             InputDebounce                **/
/**********************************************/
void InputDebounce(void)
{
	static char RUN_PB_DebounceCnt = 0;
	static char CAM_SETUP_PB_DebounceCnt = 0;
	static char AUTO_PB_DebounceCnt = 0;
	static char MANUAL_PB_DebounceCnt = 0;
	static char CLOSE_PB_DebounceCnt = 0;
	static char OPEN_PB_DebounceCnt = 0;
	static char NUDGE_PB_DebounceCnt = 0;
	static char HEAVY_PB_DebounceCnt = 0;
	static char CLOSE_DebounceCnt = 0;
	static char OPEN_DebounceCnt = 0;
	static char NUDGE_DebounceCnt = 0;
	static char HEAVY_DebounceCnt = 0;
	//-static char GSM_DebounceCnt = 0;
//-	static char AUX_DebounceCnt = 0;
//-	static char SSFO_IN_DebounceCnt = 0;
//-	static char SDO_IN_DebounceCnt = 0;
//-	static char SDC_IN_DebounceCnt = 0;
	static char DOL_DebounceCnt = 0;
	static char DCL_DebounceCnt = 0;
	static char REOPEN_DebounceCnt = 0;
	static char REOPEN_DebounceCnt_LCSE=0;

	static char CAN_BR_HLD_DebounceCnt=0;




	if(InputDebounceEna == 1)
	{
	    //-------------------------------------------------------------
	    //Switch
	    //Run Switch
		if(RUN_PB_HOLD == 1)
		{
			if (RUN_PB_DebounceCnt > 2)
				RUN_PB = 1;
			else
				RUN_PB_DebounceCnt++;
		}
		else
		{
			if (RUN_PB_DebounceCnt <= 0)
			{
				RUN_PB = 0;
				RUN_PB_DebounceCnt = 0;
			}
			else
				RUN_PB_DebounceCnt--;
		}


		//Setup Switch
		if(CAM_SETUP_PB_HOLD == 1)
		{
			if (CAM_SETUP_PB_DebounceCnt > 2)
				CAM_SETUP_PB = 1;
			else
				CAM_SETUP_PB_DebounceCnt++;
		}
		else
		{
			if (CAM_SETUP_PB_DebounceCnt <= 0)
			{
				CAM_SETUP_PB = 0;
				CAM_SETUP_PB_DebounceCnt = 0;
			}
			else
				CAM_SETUP_PB_DebounceCnt--;

		}


		//Auto Switch
		if(AUTO_PB_HOLD == 1)
		{

			if (AUTO_PB_DebounceCnt > 2)
				AUTO_PB = 1;
			else
				AUTO_PB_DebounceCnt++;
		}
		else
		{
			if (AUTO_PB_DebounceCnt <= 0)
			{
				AUTO_PB = 0;
				AUTO_PB_DebounceCnt = 0;
			}
			else
				AUTO_PB_DebounceCnt--;

		}


		//Manual Switch
		if(MANUAL_PB_HOLD == 1)
		{
			if (MANUAL_PB_DebounceCnt > 2)
				MANUAL_PB = 1;
			else
				MANUAL_PB_DebounceCnt++;
		}
		else
		{
			if (MANUAL_PB_DebounceCnt <= 0)
			{
				MANUAL_PB = 0;
				MANUAL_PB_DebounceCnt = 0;
			}
			else
				MANUAL_PB_DebounceCnt--;
		}


		//-------------------------------------------------------------
		//Push Button
		//Close Push Button
		if(CLOSE_PB_HOLD == 1)
		{
			if (CLOSE_PB_DebounceCnt > 1)
				CLOSE_PB = 1;
			else
				CLOSE_PB_DebounceCnt++;
		}
		else
		{
			if (CLOSE_PB_DebounceCnt <= 0)
			{
				CLOSE_PB = 0;
				CLOSE_PB_DebounceCnt = 0;
			}
			else
				CLOSE_PB_DebounceCnt--;
		}


		//Open Push Button
		if(OPEN_PB_HOLD == 1)
		{
			if (OPEN_PB_DebounceCnt > 1)
				OPEN_PB = 1;
			else
				OPEN_PB_DebounceCnt++;
		}
		else
		{
			if (OPEN_PB_DebounceCnt <= 0)
			{
				OPEN_PB = 0;
				OPEN_PB_DebounceCnt = 0;
			}
			else
				OPEN_PB_DebounceCnt--;
		}


		//Nudging Push Button
		if(NUDGE_PB_HOLD == 1)
		{
			if (NUDGE_PB_DebounceCnt > 1)
				NUDGE_PB = 1;
			else
				NUDGE_PB_DebounceCnt++;
		}
		else
		{
			if (NUDGE_PB_DebounceCnt <= 0)
			{
				NUDGE_PB = 0;
				NUDGE_PB_DebounceCnt = 0;
			}
			else
				NUDGE_PB_DebounceCnt--;
		}


		//Heavy Push Button
		if(HEAVY_PB_HOLD == 1)
		{
			if (HEAVY_PB_DebounceCnt > 1)
				HEAVY_PB = 1;
			else
				HEAVY_PB_DebounceCnt++;
		}
		else
		{
			if (HEAVY_PB_DebounceCnt <= 0)
			{
				HEAVY_PB = 0;
				HEAVY_PB_DebounceCnt = 0;
			}
			else
				HEAVY_PB_DebounceCnt--;
		}


		//-------------------------------------------------------------
		//Input Card
		//Close Input Card
		if(CLOSE_HOLD == 1)
		{
			if (CLOSE_DebounceCnt > 1)
				CLOSE = 1;
			else
				CLOSE_DebounceCnt++;
		}
		else
		{
			if (CLOSE_DebounceCnt <= 0)
			{
				CLOSE = 0;
				CLOSE_DebounceCnt = 0;
			}
			else
				CLOSE_DebounceCnt--;
		}


		//Open Input Card
		if(OPEN_HOLD == 1)
		{
			if (OPEN_DebounceCnt > 1)
				OPEN = 1;
			else
				OPEN_DebounceCnt++;
		}
		else
		{
			if (OPEN_DebounceCnt <= 0)
			{
				OPEN = 0;
				OPEN_DebounceCnt = 0;
			}
			else
				OPEN_DebounceCnt--;

		}


		//Nudging Input Card
		if(NUDGE_HOLD == 1)
		{
			if (NUDGE_DebounceCnt > 1)
				NUDGE = 1;
			else
				NUDGE_DebounceCnt++;
		}
		else
		{
			if (NUDGE_DebounceCnt <= 0)
			{
				NUDGE = 0;
				NUDGE_DebounceCnt = 0;
			}
			else
				NUDGE_DebounceCnt--;
		}


		//Heavy Input Card
		if(HEAVY_HOLD == 1)
		{
			if (HEAVY_DebounceCnt > 1)
				HEAVY = 1;
			else
				HEAVY_DebounceCnt++;
		}
		else
		{
			if (HEAVY_DebounceCnt <= 0)
			{
				HEAVY = 0;
				HEAVY_DebounceCnt = 0;
			}
			else
				HEAVY_DebounceCnt--;
		}



//Modify
/*//-
		//-------------------------------------------------------------
		//CAM
		//DPM CAM
		if(GSM_HOLD == 1)
		{
			if (GSM_DebounceCnt > 1)
				GSM = 1;
			else
				GSM_DebounceCnt++;

		}
		else
		{
			if (GSM_DebounceCnt <= 0)
			{
				GSM = 0;
				GSM_DebounceCnt = 0;
			}
			else
				GSM_DebounceCnt--;
		}



		//AUX CAM
		if(AUX_HOLD == 1)
		{
			if (AUX_DebounceCnt > 1)
				AUX = 1;
			else
				AUX_DebounceCnt++;

		}
		else
		{
			if (AUX_DebounceCnt <= 0)
			{
				AUX = 0;
				AUX_DebounceCnt = 0;
			}
			else
				AUX_DebounceCnt--;
		}


		//SSO/FSO CAM
		if(SSFO_IN_HOLD == 1)
		{
			if (SSFO_IN_DebounceCnt > 1)
				SSFO_IN = 1;
			else
				SSFO_IN_DebounceCnt++;
		}
		else
		{
			if (SSFO_IN_DebounceCnt <= 0)
			{
				SSFO_IN = 0;
				SSFO_IN_DebounceCnt = 0;
			}
			else
				SSFO_IN_DebounceCnt--;
		}


		//MSO CAM
		if(SDO_IN_HOLD == 1)
		{
			if (SDO_IN_DebounceCnt > 1)
 				SDO_IN = 1;
			else
				SDO_IN_DebounceCnt++;
		}
		else
		{
			if (SDO_IN_DebounceCnt <= 0)
			{
				SDO_IN = 0;
				SDO_IN_DebounceCnt = 0;
			}
			else
				SDO_IN_DebounceCnt--;
		}


		//FSC CAM
		if(SDC_IN_HOLD == 1)
		{
			if (SDC_IN_DebounceCnt > 1)
				SDC_IN = 1;
			else
				SDC_IN_DebounceCnt++;
		}
		else
		{
			if (SDC_IN_DebounceCnt <= 0)
			{
				SDC_IN = 0;
				SDC_IN_DebounceCnt = 0;
			}
			else
				SDC_IN_DebounceCnt--;
		}
*/

		//DOL CAM
		if(DOL_HOLD == 1)
		{
			if (DOL_DebounceCnt > 1)
				DOL = 1;
			else
				DOL_DebounceCnt++;
		}
		else
		{
			if (DOL_DebounceCnt <= 0)
			{
				DOL = 0;
				DOL_DebounceCnt = 0;
			}
			else
				DOL_DebounceCnt--;
		}


		//DCL CAM
		if (DCL_HOLD == 1)
		{
			if (DCL_DebounceCnt > 1)
			{
				DCL = 1;
//Modify
//-				GSM=1;
			}
			else
				DCL_DebounceCnt++;
		}
		else
		{
			if (DCL_DebounceCnt <= 0)
			{
				DCL = 0;
				DCL_DebounceCnt = 0;
//Modify
//-				GSM=0;
			}
			else
				DCL_DebounceCnt--;
		}


		//-------------------------------------------------------------
		//Reopen From Siemens Drive
		if (REOPEN_HOLD == 1)
		{
			if (REOPEN_DebounceCnt > 1)
				REOPEN = 1;
			else
				REOPEN_DebounceCnt++;
		}
		else
		{
			if (REOPEN_DebounceCnt <= 0)
			{
				REOPEN = 0;
				REOPEN_DebounceCnt = 0;
			}
			else
				REOPEN_DebounceCnt--;
		}

		//Reopen From Scan Guard
		if (REOPEN_LCSE_HOLD == 1)
		{
			if (REOPEN_DebounceCnt_LCSE > 1)
				REOPEN_LCSE = 1;
			else
				REOPEN_DebounceCnt_LCSE++;
		}
		else
		{
			if (REOPEN_DebounceCnt_LCSE <= 0)
			{
				REOPEN_LCSE = 0;
				REOPEN_DebounceCnt_LCSE = 0;
			}
			else
				REOPEN_DebounceCnt_LCSE--;
		}


		//-------------------------------------------------------------
		//GAL CAN Baud Rate flag 1 -->  57.6k    0 --> 115.2k
		if (CAN_BaudRate_HOLD == 1)
		{
			if (CAN_BR_HLD_DebounceCnt > 1)
				CAN_BaudRate_flag = 1;
			else
				CAN_BR_HLD_DebounceCnt++;
		}
		else
		{
			if (CAN_BR_HLD_DebounceCnt <= 0)
			{
				CAN_BaudRate_flag = 0;
				CAN_BR_HLD_DebounceCnt = 0;
			}
			else
				CAN_BR_HLD_DebounceCnt--;
		}




		InputDebounceEna = 0;
		FR_Jumper = FR_Signal;  // Front Rear  Address  Jumper
	}
}



/*
 	 	 	 	 	 	 	 	 	 	 	 Version Control


 Date:			Version:		Author:		Changes:

 	 1/19/2015		V1.13			WC			1. Remove saving RUN, CAM, AUTO and Manual since  hardware  changed
   	   	   	   	   	   	   	   	   	   	   		2. ReMap IO

	 2/16/2015      V1.14           WC          1. Check  for Rear Door Address
	 9/10/2015      V1.16  		    WC   		1. Refactor  Can.c  model

	10/20/2015      V1.19           WC          1. Added a  1 second WatchDog timer
	11/01/2015      V1.20           WC          1. If manual SW  or  CamSetup SW  is  on,  blink Diag  and Comm Led  faster

 */



